import { useState } from "react";
import PropTypes from "prop-types";
import "./ReportExport.css";

/**
 * Allows downloading report artifacts generated by the backend.
 */
function ReportExport({ videoId = "", onExport = () => {} }) {
  const [exporting, setExporting] = useState(null);

  const handleExport = async (format) => {
    if (!videoId) return;
    setExporting(format);
    try {
      await onExport(videoId, format);
    } finally {
      setExporting(null);
    }
  };

  return (
    <div className="report-export">
      <h3>Export Results</h3>
      <div className="report-export-actions">
        <button 
          onClick={() => handleExport("html")} 
          disabled={!videoId || exporting}
          className={exporting === "html" ? "exporting" : ""}
        >
          {exporting === "html" ? "Exporting..." : "📄 HTML Report"}
        </button>
        <button 
          onClick={() => handleExport("pdf")} 
          disabled={!videoId || exporting}
          className={exporting === "pdf" ? "exporting" : ""}
        >
          {exporting === "pdf" ? "Exporting..." : "📑 PDF Report"}
        </button>
        <button 
          onClick={() => handleExport("csv")} 
          disabled={!videoId || exporting}
          className={exporting === "csv" ? "exporting" : ""}
        >
          {exporting === "csv" ? "Exporting..." : "📊 CSV Data"}
        </button>
      </div>
    </div>
  );
}

ReportExport.propTypes = {
  videoId: PropTypes.string,
  onExport: PropTypes.func
};

export default ReportExport;

